/**
 * Exercise database — DEPRECATED.
 * 
 * Diese eingebauten Testübungen werden nicht mehr als Fallback geladen.
 * Übungen werden ausschließlich aus /assets/data/exercises.json geladen.
 * 
 * Diese Datei wird nur noch für die `getPrimaryCategory()` Utility-Funktion verwendet.
 */

export const DEFAULT_EXERCISES = [
  // === BODY WEIGHT ===
  { index: 10000, name: "Plank", categories: ["Body Weight", "Core"], muscles: ["core","shoulders","back"], musclesLatin: ["musculus rectus abdominis / transversus abdominis","musculus deltoideus","musculus erector spinae"], shortDescription: "Halte deinen Körper in einer geraden Linie, gestützt auf Unterarme und Zehen. Spanne Rumpf und Gesäß an.", notes: "Hüfte nicht durchhängen lassen. Blick nach unten richten.", animationKey: "plank" },
  { index: 10001, name: "Push-Ups", categories: ["Body Weight", "Chest"], muscles: ["chest","triceps","shoulders","core"], musclesLatin: ["musculus pectoralis major","musculus triceps brachii","musculus deltoideus","musculus rectus abdominis"], shortDescription: "Aus der Liegestützposition senke deinen Körper kontrolliert ab und drücke dich wieder hoch.", notes: "Ellbogen nicht zu weit abspreizen. Körper gerade halten.", animationKey: "pushup" },
  { index: 10002, name: "Squats", categories: ["Body Weight", "Legs"], muscles: ["quadriceps","glutes","hamstrings"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus","musculi ischiocrurale"], shortDescription: "Stehe schulterbreit, senke deine Hüfte ab als würdest du dich auf einen Stuhl setzen.", notes: "Knie nicht über die Zehenspitzen hinaus. Rücken gerade halten.", animationKey: "squat" },
  { index: 10003, name: "Lunges", categories: ["Body Weight", "Legs"], muscles: ["quadriceps","glutes","hamstrings"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus","musculi ischiocrurale"], shortDescription: "Mache einen großen Schritt nach vorne und senke das hintere Knie Richtung Boden.", notes: "Oberkörper aufrecht halten. Vorderes Knie über dem Knöchel.", animationKey: "lunge" },
  { index: 10004, name: "Step-Back Lunges", categories: ["Body Weight", "Legs"], muscles: ["quadriceps","glutes","hamstrings"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus","musculi ischiocrurale"], shortDescription: "Mache einen großen Schritt nach hinten und senke das hintere Knie Richtung Boden.", notes: "Oberkörper aufrecht halten. Kontrollierte Bewegung.", animationKey: "lunge" },
  { index: 10005, name: "Burpees", categories: ["Body Weight", "Cardio"], muscles: ["full-body"], musclesLatin: ["musculi corporis totius"], shortDescription: "Aus dem Stand in die Hocke, Hände auf den Boden, Beine zurückspringen, Liegestütz, zurückspringen, aufspringen.", notes: "Flüssige Bewegung. Bei Knieproblemen den Sprung weglassen.", animationKey: "burpee" },
  { index: 10006, name: "Mountain Climbers", categories: ["Body Weight", "Core"], muscles: ["core","shoulders","hip-flexors"], musclesLatin: ["musculus rectus abdominis","musculus deltoideus","musculus iliopsoas"], shortDescription: "In der Liegestützposition abwechselnd die Knie zur Brust ziehen.", notes: "Hüfte nicht zu hoch nehmen. Gleichmäßiges Tempo.", animationKey: "mountain_climber" },
  { index: 10007, name: "Hip Thrust", categories: ["Body Weight", "Glutes"], muscles: ["glutes","hamstrings"], musclesLatin: ["musculus gluteus maximus","musculi ischiocrurale"], shortDescription: "Lehne dich mit dem oberen Rücken an eine Bank, Füße flach auf dem Boden. Hebe die Hüfte an und drücke das Gesäß zusammen.", notes: "Am höchsten Punkt Gesäß fest anspannen. Kinn zur Brust.", animationKey: "hip_thrust" },
  { index: 10008, name: "Glute Bridge", categories: ["Body Weight", "Glutes"], muscles: ["glutes","hamstrings","core"], musclesLatin: ["musculus gluteus maximus","musculi ischiocrurale","musculus rectus abdominis"], shortDescription: "Auf dem Rücken liegend, Füße aufgestellt, hebe die Hüfte an und spanne das Gesäß an.", notes: "Langsam und kontrolliert. Gesäß oben kurz halten.", animationKey: "glute_bridge" },
  { index: 10009, name: "Single Leg Romanian Deadlift", categories: ["Body Weight", "Legs"], muscles: ["hamstrings","glutes","core"], musclesLatin: ["musculi ischiocrurale","musculus gluteus maximus","musculus rectus abdominis"], shortDescription: "Stehe auf einem Bein, beuge dich nach vorne und strecke das andere Bein nach hinten.", notes: "Rücken gerade halten. Langsame, kontrollierte Bewegung.", animationKey: "single_leg_deadlift" },
  { index: 10010, name: "Lateral Leg Raise", categories: ["Body Weight", "Glutes"], muscles: ["hip-abductors","glutes"], musclesLatin: ["musculus gluteus medius / minimus","musculus gluteus maximus"], shortDescription: "Auf der Seite liegend, hebe das obere Bein kontrolliert an und senke es wieder.", notes: "Bein gestreckt halten. Nicht mit Schwung arbeiten.", animationKey: "lateral_leg_raise" },
  { index: 10011, name: "Lateral Shoulder Raises", categories: ["Body Weight", "Shoulders"], muscles: ["shoulders"], musclesLatin: ["musculus deltoideus (pars acromialis)"], shortDescription: "Stehe aufrecht, hebe die Arme seitlich bis auf Schulterhöhe an.", notes: "Leicht gebeugte Ellbogen. Kontrolliert absenken.", animationKey: "lateral_raise" },
  { index: 10012, name: "Dead Bug", categories: ["Body Weight", "Core"], muscles: ["core","hip-flexors"], musclesLatin: ["musculus rectus abdominis / transversus abdominis","musculus iliopsoas"], shortDescription: "Auf dem Rücken liegend, Arme und Beine in der Luft. Strecke abwechselnd gegenüberliegenden Arm und Bein aus.", notes: "Unteren Rücken fest auf dem Boden pressen.", animationKey: "dead_bug" },
  { index: 10013, name: "Superman", categories: ["Body Weight", "Back"], muscles: ["back-lower","glutes"], musclesLatin: ["musculus erector spinae","musculus gluteus maximus"], shortDescription: "Auf dem Bauch liegend, hebe gleichzeitig Arme und Beine vom Boden ab.", notes: "Nicht den Nacken überstrecken. Blick zum Boden.", animationKey: "superman" },
  { index: 10014, name: "Bicycle Crunches", categories: ["Body Weight", "Core"], muscles: ["abs","obliques"], musclesLatin: ["musculus rectus abdominis","musculus obliquus externus abdominis"], shortDescription: "Auf dem Rücken, führe abwechselnd Ellbogen und gegenüberliegendes Knie zusammen.", notes: "Nicht am Nacken ziehen. Schulterblätter vom Boden lösen.", animationKey: "bicycle_crunch" },
  { index: 10015, name: "Jumping Jacks", categories: ["Body Weight", "Cardio"], muscles: ["full-body"], musclesLatin: ["musculi corporis totius"], shortDescription: "Springe in den Grätschstand mit Armen über dem Kopf, springe zurück in die Ausgangsposition.", notes: "Weiche Landung. Gleichmäßiges Tempo.", animationKey: "jumping_jack" },
  { index: 10016, name: "High Knees", categories: ["Body Weight", "Cardio"], muscles: ["hip-flexors","quadriceps"], musclesLatin: ["musculus iliopsoas","musculus quadriceps femoris"], shortDescription: "Laufe auf der Stelle und ziehe die Knie abwechselnd hoch zur Brust.", notes: "Aufrechter Oberkörper. Arme mitschwingen.", animationKey: "high_knees" },
  { index: 10017, name: "Tricep Dips", categories: ["Body Weight", "Arms"], muscles: ["triceps","shoulders","chest"], musclesLatin: ["musculus triceps brachii","musculus deltoideus","musculus pectoralis major"], shortDescription: "Stütze dich auf einer Kante ab, senke deinen Körper durch Beugen der Arme und drücke dich wieder hoch.", notes: "Ellbogen nach hinten, nicht zur Seite. Nicht zu tief senken.", animationKey: "tricep_dip" },
  { index: 10018, name: "Crunches", categories: ["Body Weight", "Core"], muscles: ["abs"], musclesLatin: ["musculus rectus abdominis"], shortDescription: "Auf dem Rücken liegend, Knie angewinkelt, hebe den Oberkörper leicht an.", notes: "Nicht am Nacken ziehen. Kontrollierte Bewegung.", animationKey: "crunch" },
  { index: 10019, name: "Wall Sit", categories: ["Body Weight", "Legs"], muscles: ["quadriceps","glutes"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus"], shortDescription: "Lehne dich mit dem Rücken an eine Wand und senke dich in eine sitzende Position ab.", notes: "Knie im 90-Grad-Winkel. Rücken flach an der Wand.", animationKey: "wall_sit" },
  { index: 10020, name: "Donkey Kicks", categories: ["Body Weight", "Glutes"], muscles: ["glutes","hamstrings"], musclesLatin: ["musculus gluteus maximus","musculi ischiocrurale"], shortDescription: "Im Vierfüßlerstand, kicke ein Bein nach oben zur Decke.", notes: "Rücken nicht durchhängen lassen. Kontrollierte Bewegung.", animationKey: "donkey_kick" },
  { index: 10021, name: "Calf Raises", categories: ["Body Weight", "Legs"], muscles: ["calves"], musclesLatin: ["musculus gastrocnemius / musculus soleus"], shortDescription: "Stehe aufrecht und drücke dich auf die Zehenspitzen hoch.", notes: "Langsam hochdrücken und kontrolliert absenken.", animationKey: "calf_raise" },
  { index: 10022, name: "Side Plank", categories: ["Body Weight", "Core"], muscles: ["obliques","core"], musclesLatin: ["musculus obliquus externus abdominis","musculus transversus abdominis"], shortDescription: "Stütze dich seitlich auf einen Unterarm, halte den Körper in einer geraden Linie.", notes: "Hüfte nicht absinken lassen. Schulter über dem Ellbogen.", animationKey: "side_plank" },
  { index: 10023, name: "Reverse Lunges", categories: ["Body Weight", "Legs"], muscles: ["quadriceps","glutes","hamstrings"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus","musculi ischiocrurale"], shortDescription: "Mache einen großen Schritt nach hinten, senke das hintere Knie Richtung Boden.", notes: "Oberkörper aufrecht. Gleichgewicht halten.", animationKey: "lunge" },
  { index: 10024, name: "Flutter Kicks", categories: ["Body Weight", "Core"], muscles: ["abs-lower","hip-flexors"], musclesLatin: ["musculus rectus abdominis (pars inferior)","musculus iliopsoas"], shortDescription: "Auf dem Rücken liegend, Beine leicht angehoben, abwechselnd kleine Auf-Ab-Bewegungen.", notes: "Unteren Rücken auf dem Boden halten.", animationKey: "flutter_kick" },
  { index: 10025, name: "Bear Crawl", categories: ["Body Weight", "Core"], muscles: ["core","shoulders","full-body"], musclesLatin: ["musculus transversus abdominis","musculus deltoideus","musculi corporis totius"], shortDescription: "Im Vierfüßlerstand mit angehobenen Knien vorwärts bewegen.", notes: "Knie nur wenige Zentimeter über dem Boden. Rücken flach.", animationKey: "bear_crawl" },
  { index: 10026, name: "Inchworm", categories: ["Body Weight", "Core"], muscles: ["core","shoulders","hamstrings"], musclesLatin: ["musculus rectus abdominis","musculus deltoideus","musculi ischiocrurale"], shortDescription: "Aus dem Stand vorwärts in die Liegestützposition wandern und wieder zurück.", notes: "Beine möglichst gestreckt halten.", animationKey: "inchworm" },
  { index: 10027, name: "Box Jumps", categories: ["Body Weight", "Legs"], muscles: ["quadriceps","calves","glutes"], musclesLatin: ["musculus quadriceps femoris","musculus gastrocnemius","musculus gluteus maximus"], shortDescription: "Springe aus dem Stand auf eine erhöhte Plattform und steige kontrolliert ab.", notes: "Weich landen mit gebeugten Knien.", animationKey: "box_jump" },
  { index: 10028, name: "Sit-Ups", categories: ["Body Weight", "Core"], muscles: ["abs","hip-flexors"], musclesLatin: ["musculus rectus abdominis","musculus iliopsoas"], shortDescription: "Auf dem Rücken liegend, Füße fixiert, hebe den gesamten Oberkörper zum Sitzen an.", notes: "Nicht am Nacken ziehen. Kontrolliert ablegen.", animationKey: "situp" },
  { index: 10029, name: "Leg Raises", categories: ["Body Weight", "Core"], muscles: ["abs-lower","hip-flexors"], musclesLatin: ["musculus rectus abdominis (pars inferior)","musculus iliopsoas"], shortDescription: "Auf dem Rücken liegend, hebe gestreckte Beine bis zur Senkrechten an.", notes: "Unteren Rücken fest am Boden lassen.", animationKey: "leg_raise" },
  { index: 10030, name: "Pike Push-Ups", categories: ["Body Weight", "Shoulders"], muscles: ["shoulders","triceps"], musclesLatin: ["musculus deltoideus","musculus triceps brachii"], shortDescription: "In einer umgekehrten V-Position, senke den Kopf zum Boden und drücke dich hoch.", notes: "Blick zu den Füßen. Ellbogen kontrolliert beugen.", animationKey: "pike_pushup" },

  // === RESISTANCE BANDS ===
  { index: 10031, name: "Clamshell", categories: ["Resistance Bands", "Glutes"], muscles: ["hip-abductors","glutes"], musclesLatin: ["musculus gluteus medius / minimus","musculus gluteus maximus"], shortDescription: "Auf der Seite liegend, Knie angewinkelt, Band um die Knie. Öffne das obere Knie wie eine Muschel.", notes: "Füße zusammenlassen. Langsam und kontrolliert.", animationKey: "clamshell" },
  { index: 10032, name: "Banded Glute Bridge", categories: ["Resistance Bands", "Glutes"], muscles: ["glutes","hamstrings"], musclesLatin: ["musculus gluteus maximus","musculi ischiocrurale"], shortDescription: "Band um die Knie, auf dem Rücken liegend, Hüfte anheben und Knie nach außen drücken.", notes: "Knie aktiv nach außen drücken gegen das Band.", animationKey: "banded_glute_bridge" },
  { index: 10033, name: "Seated Band Hold", categories: ["Resistance Bands", "Glutes"], muscles: ["hip-abductors","glutes"], musclesLatin: ["musculus gluteus medius","musculus gluteus maximus"], shortDescription: "Sitzend, Band um die Knie, Knie nach außen drücken und Position halten.", notes: "Aufrechter Oberkörper. Gleichmäßiger Druck nach außen.", animationKey: "seated_band_hold" },
  { index: 10034, name: "Side Walks", categories: ["Resistance Bands", "Glutes"], muscles: ["hip-abductors","glutes"], musclesLatin: ["musculus gluteus medius","musculus gluteus maximus"], shortDescription: "Band um die Knöchel, in leichter Hocke seitlich gehen.", notes: "In der Hocke bleiben. Kontrollierte Schritte.", animationKey: "side_walk" },
  { index: 10035, name: "Fire Hydrant", categories: ["Resistance Bands", "Glutes"], muscles: ["glutes","hip-abductors"], musclesLatin: ["musculus gluteus maximus","musculus gluteus medius"], shortDescription: "Im Vierfüßlerstand, Band um die Knie, hebe ein Knie seitlich an.", notes: "Rumpf stabil halten. Nicht zur Seite kippen.", animationKey: "fire_hydrant" },
  { index: 10036, name: "Standing Hip Abduction", categories: ["Resistance Bands", "Glutes"], muscles: ["hip-abductors","glutes"], musclesLatin: ["musculus gluteus medius","musculus gluteus maximus"], shortDescription: "Stehend, Band um die Knöchel, führe ein Bein seitlich nach außen.", notes: "Oberkörper aufrecht. Standbein leicht gebeugt.", animationKey: "hip_abduction" },
  { index: 10037, name: "Banded Dead Bug", categories: ["Resistance Bands", "Core"], muscles: ["core","hip-flexors"], musclesLatin: ["musculus transversus abdominis","musculus iliopsoas"], shortDescription: "Auf dem Rücken, Band um die Hände, strecke gegenüberliegenden Arm und Bein aus.", notes: "Band unter Spannung halten. Rücken am Boden.", animationKey: "banded_dead_bug" },
  { index: 10038, name: "Pallof Press", categories: ["Resistance Bands", "Core"], muscles: ["core","obliques"], musclesLatin: ["musculus transversus abdominis","musculus obliquus externus abdominis"], shortDescription: "Band seitlich befestigt, drücke die Hände gerade von der Brust nach vorne.", notes: "Dem Zug des Bandes widerstehen. Rumpf stabil.", animationKey: "pallof_press" },
  { index: 10039, name: "Banded Pull-Aparts", categories: ["Resistance Bands", "Back"], muscles: ["back-upper","shoulders"], musclesLatin: ["musculus trapezius / musculi rhomboidei","musculus deltoideus (pars spinalis)"], shortDescription: "Band vor der Brust halten, Arme seitlich auseinanderziehen.", notes: "Schulterblätter zusammenziehen. Arme gestreckt.", animationKey: "band_pull_apart" },
  { index: 10040, name: "Banded Squat", categories: ["Resistance Bands", "Legs"], muscles: ["quadriceps","glutes"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus"], shortDescription: "Band um die Knie, führe eine Kniebeuge aus und drücke die Knie aktiv nach außen.", notes: "Knie über den Zehen, aktiv nach außen gegen das Band.", animationKey: "banded_squat" },
  { index: 10041, name: "Banded Bicep Curl", categories: ["Resistance Bands", "Arms"], muscles: ["biceps"], musclesLatin: ["musculus biceps brachii"], shortDescription: "Stehe auf dem Band, halte die Enden und curle die Arme hoch.", notes: "Ellbogen am Körper lassen. Kontrolliert absenken.", animationKey: "bicep_curl" },
  { index: 10042, name: "Banded Shoulder Press", categories: ["Resistance Bands", "Shoulders"], muscles: ["shoulders","triceps"], musclesLatin: ["musculus deltoideus","musculus triceps brachii"], shortDescription: "Stehe auf dem Band, drücke die Enden über den Kopf.", notes: "Core anspannen. Nicht ins Hohlkreuz gehen.", animationKey: "shoulder_press" },
  { index: 10043, name: "Banded Lateral Walk", categories: ["Resistance Bands", "Glutes"], muscles: ["glutes","hip-abductors"], musclesLatin: ["musculus gluteus maximus","musculus gluteus medius"], shortDescription: "Band um die Knöchel, in leichter Hocke seitlich gehen.", notes: "Spannung im Band halten. Kleine, kontrollierte Schritte.", animationKey: "lateral_walk" },
  { index: 10044, name: "Banded Kickback", categories: ["Resistance Bands", "Glutes"], muscles: ["glutes","hamstrings"], musclesLatin: ["musculus gluteus maximus","musculi ischiocrurale"], shortDescription: "Im Vierfüßlerstand, Band um den Fuß, trete ein Bein nach hinten aus.", notes: "Bein gestreckt nach hinten. Rücken gerade.", animationKey: "banded_kickback" },
  { index: 10045, name: "Banded Rows", categories: ["Resistance Bands", "Back"], muscles: ["back","biceps","lats"], musclesLatin: ["musculus trapezius / musculi rhomboidei","musculus biceps brachii","musculus latissimus dorsi"], shortDescription: "Band vor dir befestigt, ziehe die Enden zum Körper.", notes: "Schulterblätter zusammenziehen. Ellbogen nah am Körper.", animationKey: "banded_row" },
  { index: 10046, name: "Banded Chest Press", categories: ["Resistance Bands", "Chest"], muscles: ["chest","triceps","shoulders"], musclesLatin: ["musculus pectoralis major","musculus triceps brachii","musculus deltoideus"], shortDescription: "Band hinter dem Rücken, drücke die Enden nach vorne.", notes: "Kontrolliert drücken und zurücknehmen.", animationKey: "chest_press" },
  { index: 10047, name: "Banded Front Raise", categories: ["Resistance Bands", "Shoulders"], muscles: ["shoulders"], musclesLatin: ["musculus deltoideus (pars clavicularis)"], shortDescription: "Stehe auf dem Band, hebe die Arme gestreckt nach vorne.", notes: "Nicht über Schulterhöhe. Kontrolliert absenken.", animationKey: "front_raise" },
  { index: 10048, name: "Banded Tricep Extension", categories: ["Resistance Bands", "Arms"], muscles: ["triceps"], musclesLatin: ["musculus triceps brachii"], shortDescription: "Band hinter dem Kopf, strecke die Arme nach oben.", notes: "Ellbogen nah am Kopf. Nur die Unterarme bewegen.", animationKey: "tricep_extension" },
  { index: 10049, name: "Banded Good Morning", categories: ["Resistance Bands", "Back"], muscles: ["hamstrings","back-lower","glutes"], musclesLatin: ["musculi ischiocrurale","musculus erector spinae","musculus gluteus maximus"], shortDescription: "Band unter den Füßen und um den Nacken, beuge dich mit geradem Rücken nach vorne.", notes: "Rücken gerade halten. Knie leicht gebeugt.", animationKey: "good_morning" },
  { index: 10050, name: "Banded Monster Walk", categories: ["Resistance Bands", "Glutes"], muscles: ["glutes","hip-abductors"], musclesLatin: ["musculus gluteus maximus","musculus gluteus medius"], shortDescription: "Band um die Knöchel, gehe in der Hocke diagonal vorwärts.", notes: "In der Hocke bleiben. Große diagonale Schritte.", animationKey: "monster_walk" },
  { index: 10051, name: "Banded Face Pull", categories: ["Resistance Bands", "Shoulders"], muscles: ["shoulders","back-upper"], musclesLatin: ["musculus deltoideus (pars spinalis)","musculus trapezius / musculi rhomboidei"], shortDescription: "Band auf Gesichtshöhe befestigt, ziehe es mit beiden Händen zum Gesicht.", notes: "Ellbogen hoch. Schulterblätter zusammenziehen.", animationKey: "face_pull" },
  { index: 10052, name: "Banded Woodchop", categories: ["Resistance Bands", "Core"], muscles: ["core","obliques"], musclesLatin: ["musculus transversus abdominis","musculus obliquus externus abdominis"], shortDescription: "Band unten befestigt, ziehe es diagonal von unten nach oben.", notes: "Rotation aus der Hüfte. Arme gestreckt.", animationKey: "woodchop" },
  { index: 10053, name: "Banded External Rotation", categories: ["Resistance Bands", "Shoulders"], muscles: ["rotator-cuff"], musclesLatin: ["musculi rotatorii humeri (supraspinatus, infraspinatus, teres minor, subscapularis)"], shortDescription: "Band vor dir, Ellbogen am Körper, drehe den Unterarm nach außen.", notes: "Ellbogen fest am Körper. Langsame Bewegung.", animationKey: "external_rotation" },
  { index: 10054, name: "Banded Hip Flexion", categories: ["Resistance Bands", "Legs"], muscles: ["hip-flexors"], musclesLatin: ["musculus iliopsoas"], shortDescription: "Band um den Fuß, hebe das Knie gegen den Widerstand an.", notes: "Oberkörper aufrecht. Kontrollierte Bewegung.", animationKey: "hip_flexion" },
  { index: 10055, name: "Banded Leg Press", categories: ["Resistance Bands", "Legs"], muscles: ["quadriceps","glutes"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus"], shortDescription: "Auf dem Rücken liegend, Band um die Füße, drücke die Beine nach vorne.", notes: "Knie nicht komplett durchstrecken.", animationKey: "leg_press" },
  { index: 10056, name: "Banded Ankle Dorsiflexion", categories: ["Resistance Bands", "Legs"], muscles: ["tibialis"], musclesLatin: ["musculus tibialis anterior"], shortDescription: "Band um den Fuß, ziehe die Zehen gegen den Widerstand zum Körper.", notes: "Langsam und kontrolliert. Fuß komplett beugen.", animationKey: "dorsiflexion" },
  { index: 10057, name: "Banded Standing Crunch", categories: ["Resistance Bands", "Core"], muscles: ["abs"], musclesLatin: ["musculus rectus abdominis"], shortDescription: "Band oben befestigt, ziehe es mit den Händen hinter dem Kopf nach unten in eine Crunch-Bewegung.", notes: "Aus dem Bauch heraus bewegen, nicht aus den Armen.", animationKey: "standing_crunch" },
  { index: 10058, name: "Banded Reverse Fly", categories: ["Resistance Bands", "Shoulders"], muscles: ["shoulders","back-upper"], musclesLatin: ["musculus deltoideus (pars spinalis)","musculus trapezius"], shortDescription: "Band vor dir, Arme gestreckt nach hinten auseinanderziehen.", notes: "Kontrolliert. Schulterblätter zusammenziehen.", animationKey: "reverse_fly" },
  { index: 10059, name: "Banded Hamstring Curl", categories: ["Resistance Bands", "Legs"], muscles: ["hamstrings"], musclesLatin: ["musculi ischiocrurale (biceps femoris, semitendinosus, semimembranosus)"], shortDescription: "Band um die Knöchel, auf dem Bauch liegend, ziehe die Ferse zum Gesäß.", notes: "Hüfte am Boden lassen. Langsam zurück.", animationKey: "hamstring_curl" },
  { index: 10060, name: "Banded Calf Raise", categories: ["Resistance Bands", "Legs"], muscles: ["calves"], musclesLatin: ["musculus gastrocnemius / musculus soleus"], shortDescription: "Stehe auf dem Band, drücke dich auf die Zehenspitzen.", notes: "Langsam hoch und runter. Volle Bewegungsamplitude.", animationKey: "banded_calf_raise" },

  // === BALANCE ===
  { index: 10061, name: "Marching", categories: ["Balance", "Core"], muscles: ["hip-flexors","core"], musclesLatin: ["musculus iliopsoas","musculus transversus abdominis"], shortDescription: "Marschiere auf der Stelle und hebe die Knie abwechselnd hoch.", notes: "Aufrechter Oberkörper. Arme mitschwingen.", animationKey: "marching" },
  { index: 10062, name: "Mini Squats", categories: ["Balance", "Legs"], muscles: ["quadriceps","glutes"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus"], shortDescription: "Führe flache Kniebeugen aus, nur bis zur Hälfte des Bewegungsumfangs.", notes: "Knie über den Zehen. Gleichgewicht halten.", animationKey: "mini_squat" },
  { index: 10063, name: "Single Leg Stand", categories: ["Balance", "Core"], muscles: ["core","ankle-stabilizers"], musclesLatin: ["musculus transversus abdominis","musculi peronei / musculus tibialis posterior"], shortDescription: "Stehe auf einem Bein und halte das Gleichgewicht.", notes: "Blick auf einen festen Punkt. Standbein leicht gebeugt.", animationKey: "single_leg_stand" },
  { index: 10064, name: "Heel-to-Toe Walk", categories: ["Balance", "Core"], muscles: ["core","ankle-stabilizers"], musclesLatin: ["musculus transversus abdominis","musculi peronei"], shortDescription: "Gehe in einer Linie, setze die Ferse direkt vor die Zehen des anderen Fußes.", notes: "Blick geradeaus. Arme seitlich zum Ausgleich.", animationKey: "heel_toe_walk" },
  { index: 10065, name: "Tandem Stance", categories: ["Balance", "Core"], muscles: ["core","ankle-stabilizers"], musclesLatin: ["musculus transversus abdominis","musculi peronei"], shortDescription: "Stelle einen Fuß direkt vor den anderen und halte das Gleichgewicht.", notes: "Ferse an Zehen. Blick geradeaus.", animationKey: "tandem_stance" },
  { index: 10066, name: "Clock Reach", categories: ["Balance", "Legs"], muscles: ["glutes","core","legs"], musclesLatin: ["musculus gluteus maximus","musculus transversus abdominis","musculi membri inferioris"], shortDescription: "Stehe auf einem Bein und strecke das andere in verschiedene Richtungen wie bei einer Uhr.", notes: "Standbein stabil. Langsam bewegen.", animationKey: "clock_reach" },
  { index: 10067, name: "Stork Stand", categories: ["Balance", "Core"], muscles: ["core","calves"], musclesLatin: ["musculus transversus abdominis","musculus gastrocnemius"], shortDescription: "Stehe auf einem Bein, das andere Knie angewinkelt nach oben gezogen.", notes: "Händen in die Hüften. Aufrechte Haltung.", animationKey: "stork_stand" },
  { index: 10068, name: "Side Leg Lift Balance", categories: ["Balance", "Glutes"], muscles: ["hip-abductors","core"], musclesLatin: ["musculus gluteus medius","musculus transversus abdominis"], shortDescription: "Stehe auf einem Bein und hebe das andere Bein seitlich an.", notes: "Oberkörper aufrecht. Langsame Bewegung.", animationKey: "side_leg_balance" },
  { index: 10069, name: "Weight Shift", categories: ["Balance", "Legs"], muscles: ["core","legs"], musclesLatin: ["musculus transversus abdominis","musculi membri inferioris"], shortDescription: "Stehe breitbeinig und verlagere das Gewicht langsam von einem Bein zum anderen.", notes: "Kontrollierte Gewichtsverlagerung. Knie leicht gebeugt.", animationKey: "weight_shift" },
  { index: 10070, name: "Single Leg Deadlift Balance", categories: ["Balance", "Legs"], muscles: ["hamstrings","glutes","core"], musclesLatin: ["musculi ischiocrurale","musculus gluteus maximus","musculus transversus abdominis"], shortDescription: "Auf einem Bein stehend, beuge dich nach vorne und strecke das andere Bein nach hinten.", notes: "Langsam und kontrolliert. Rücken gerade.", animationKey: "sl_deadlift_balance" },
  { index: 10071, name: "Bosu Ball Stand", categories: ["Balance", "Core"], muscles: ["core","ankle-stabilizers"], musclesLatin: ["musculus transversus abdominis","musculi peronei"], shortDescription: "Stehe auf einer instabilen Unterlage und halte das Gleichgewicht.", notes: "Knie leicht gebeugt. Blick geradeaus.", animationKey: "bosu_stand" },
  { index: 10072, name: "Arm Circles on One Leg", categories: ["Balance", "Shoulders"], muscles: ["shoulders","core"], musclesLatin: ["musculus deltoideus","musculus transversus abdominis"], shortDescription: "Stehe auf einem Bein und mache Kreise mit den Armen.", notes: "Kleine, kontrollierte Kreise. Standbein stabil.", animationKey: "arm_circles_balance" },
  { index: 10073, name: "Step-Up Balance", categories: ["Balance", "Legs"], muscles: ["quadriceps","glutes","core"], musclesLatin: ["musculus quadriceps femoris","musculus gluteus maximus","musculus transversus abdominis"], shortDescription: "Steige auf eine Erhöhung und halte auf einem Bein oben kurz das Gleichgewicht.", notes: "Ganzer Fuß auf der Stufe. Kontrolliert absteigen.", animationKey: "step_up_balance" },
  { index: 10074, name: "Toe Tap Balance", categories: ["Balance", "Legs"], muscles: ["core","legs"], musclesLatin: ["musculus transversus abdominis","musculi membri inferioris"], shortDescription: "Stehe auf einem Bein und tippe mit dem anderen Fuß in verschiedene Richtungen.", notes: "Leichte Berührung. Standbein stabil.", animationKey: "toe_tap_balance" },
  { index: 10075, name: "Closed Eyes Balance", categories: ["Balance", "Core"], muscles: ["core","ankle-stabilizers"], musclesLatin: ["musculus transversus abdominis","musculi peronei"], shortDescription: "Stehe auf einem Bein mit geschlossenen Augen.", notes: "Sicherheitsabstand zu Gegenständen. Langsam Augen schließen.", animationKey: "eyes_closed_balance" },

  // === STRETCHING ===
  { index: 10076, name: "90/90 Hip Rotation", categories: ["Stretching", "Hips"], muscles: ["hip-rotators","glutes"], musclesLatin: ["musculi rotatorii coxae (piriformis, obturatorius internus)","musculus gluteus maximus"], shortDescription: "Sitze mit beiden Beinen im 90-Grad-Winkel und rotiere die Hüften von einer Seite zur anderen.", notes: "Rücken gerade halten. Sanft von Seite zu Seite wechseln.", animationKey: "hip_rotation_90" },
  { index: 10077, name: "Hip CARs", categories: ["Stretching", "Hips"], muscles: ["hip-rotators","glutes"], musclesLatin: ["musculi rotatorii coxae","musculus gluteus maximus"], shortDescription: "Controlled Articular Rotations: Im Vierfüßlerstand, kreise ein Knie in einem großen Bogen.", notes: "Größtmöglicher Bewegungsradius. Rumpf stabil.", animationKey: "hip_cars" },
  { index: 10078, name: "Cat-Cow Pose", categories: ["Stretching", "Back"], muscles: ["spine","core"], musclesLatin: ["musculus erector spinae","musculus transversus abdominis"], shortDescription: "Im Vierfüßlerstand abwechselnd Rücken runden (Katze) und durchhängen lassen (Kuh).", notes: "Bewegung mit der Atmung koordinieren. Langsam.", animationKey: "cat_cow" },
  { index: 10079, name: "Hamstring Stretch", categories: ["Stretching", "Legs"], muscles: ["hamstrings"], musclesLatin: ["musculi ischiocrurale"], shortDescription: "Im Sitzen oder Stehen, strecke ein Bein aus und beuge dich nach vorne.", notes: "Rücken gerade halten. Nicht federn.", animationKey: "hamstring_stretch" },
  { index: 10080, name: "Quad Stretch", categories: ["Stretching", "Legs"], muscles: ["quadriceps"], musclesLatin: ["musculus quadriceps femoris"], shortDescription: "Im Stehen, ziehe einen Fuß zum Gesäß und halte.", notes: "Knie zusammen. Hüfte nach vorne schieben.", animationKey: "quad_stretch" },
  { index: 10081, name: "Calf Stretch", categories: ["Stretching", "Legs"], muscles: ["calves"], musclesLatin: ["musculus gastrocnemius / musculus soleus"], shortDescription: "Stütze dich an einer Wand ab, ein Bein nach hinten gestreckt, drücke die Ferse in den Boden.", notes: "Hinterer Fuß zeigt geradeaus. Ferse am Boden.", animationKey: "calf_stretch" },
  { index: 10082, name: "Shoulder Stretch", categories: ["Stretching", "Shoulders"], muscles: ["shoulders","back-upper"], musclesLatin: ["musculus deltoideus","musculus trapezius / musculi rhomboidei"], shortDescription: "Ziehe einen Arm quer über die Brust und drücke ihn mit der anderen Hand.", notes: "Schulter nicht hochziehen. Sanfter Druck.", animationKey: "shoulder_stretch" },
  { index: 10083, name: "Tricep Stretch", categories: ["Stretching", "Arms"], muscles: ["triceps"], musclesLatin: ["musculus triceps brachii"], shortDescription: "Hebe einen Arm über den Kopf, beuge den Ellbogen und drücke mit der anderen Hand.", notes: "Ellbogen Richtung Decke. Sanfter Druck.", animationKey: "tricep_stretch" },
  { index: 10084, name: "Child's Pose", categories: ["Stretching", "Back"], muscles: ["back","shoulders","hip-flexors"], musclesLatin: ["musculus latissimus dorsi","musculus deltoideus","musculus iliopsoas"], shortDescription: "Knie auf dem Boden, setze dich auf die Fersen und strecke die Arme nach vorne aus.", notes: "Stirn am Boden. Tief atmen.", animationKey: "childs_pose" },
  { index: 10085, name: "Pigeon Pose", categories: ["Stretching", "Hips"], muscles: ["hip-flexors","glutes"], musclesLatin: ["musculus iliopsoas","musculus gluteus maximus"], shortDescription: "Ein Bein nach vorne angewinkelt, das andere nach hinten gestreckt. Oberkörper nach vorne beugen.", notes: "Hüfte gerade ausrichten. Langsam in die Position.", animationKey: "pigeon_pose" },
  { index: 10086, name: "Cobra Stretch", categories: ["Stretching", "Core"], muscles: ["abs","spine"], musclesLatin: ["musculus rectus abdominis","musculus erector spinae"], shortDescription: "Auf dem Bauch liegend, drücke den Oberkörper mit den Händen nach oben.", notes: "Schultern weg von den Ohren. Nicht überstrecken.", animationKey: "cobra_stretch" },
  { index: 10087, name: "Spinal Twist", categories: ["Stretching", "Back"], muscles: ["back","obliques"], musclesLatin: ["musculus erector spinae","musculus obliquus externus abdominis"], shortDescription: "Auf dem Rücken liegend, ziehe ein Knie zur gegenüberliegenden Seite.", notes: "Beide Schultern am Boden lassen. Sanft drehen.", animationKey: "spinal_twist" },
  { index: 10088, name: "Butterfly Stretch", categories: ["Stretching", "Hips"], muscles: ["hip-adductors","groin"], musclesLatin: ["musculi adductores","ligamentum inguinale"], shortDescription: "Sitzend, Fußsohlen aneinander, Knie nach außen fallen lassen.", notes: "Rücken gerade. Sanft die Knie nach unten drücken.", animationKey: "butterfly_stretch" },
  { index: 10089, name: "Standing Side Bend", categories: ["Stretching", "Core"], muscles: ["obliques","lats"], musclesLatin: ["musculus obliquus externus abdominis","musculus latissimus dorsi"], shortDescription: "Stehe aufrecht, strecke einen Arm über den Kopf und beuge dich zur Seite.", notes: "Nicht nach vorne oder hinten lehnen.", animationKey: "side_bend" },
  { index: 10090, name: "Neck Stretch", categories: ["Stretching", "Shoulders"], muscles: ["neck","traps"], musclesLatin: ["musculus trapezius (pars descendens) / m. sternocleidomastoideus","musculus trapezius"], shortDescription: "Neige den Kopf sanft zur Seite und halte die Dehnung.", notes: "Schultern unten lassen. Sanfter Zug.", animationKey: "neck_stretch" },
  { index: 10091, name: "Figure Four Stretch", categories: ["Stretching", "Glutes"], muscles: ["glutes","piriformis"], musclesLatin: ["musculus gluteus maximus","musculus piriformis"], shortDescription: "Auf dem Rücken liegend, lege einen Knöchel auf das gegenüberliegende Knie und ziehe zum Körper.", notes: "Kopf am Boden. Sanft ziehen.", animationKey: "figure_four" },
  { index: 10092, name: "Hip Flexor Stretch", categories: ["Stretching", "Hips"], muscles: ["hip-flexors"], musclesLatin: ["musculus iliopsoas"], shortDescription: "Im Ausfallschritt, drücke die Hüfte nach vorne.", notes: "Aufrechter Oberkörper. Gesäß anspannen.", animationKey: "hip_flexor_stretch" },
  { index: 10093, name: "Chest Opener", categories: ["Stretching", "Chest"], muscles: ["chest","shoulders"], musclesLatin: ["musculus pectoralis major","musculus deltoideus (pars clavicularis)"], shortDescription: "Verschränke die Hände hinter dem Rücken und ziehe die Schultern zurück.", notes: "Schulterblätter zusammenziehen. Brust öffnen.", animationKey: "chest_opener" },
  { index: 10094, name: "IT Band Stretch", categories: ["Stretching", "Legs"], muscles: ["it-band","legs"], musclesLatin: ["tractus iliotibialis","musculi membri inferioris"], shortDescription: "Stehe aufrecht, kreuze ein Bein hinter das andere und beuge dich zur Seite.", notes: "Langsam dehnen. Nicht überstrecken.", animationKey: "it_band_stretch" },
  { index: 10095, name: "Doorway Chest Stretch", categories: ["Stretching", "Chest"], muscles: ["chest","shoulders"], musclesLatin: ["musculus pectoralis major","musculus deltoideus (pars clavicularis)"], shortDescription: "Stelle dich in einen Türrahmen, Arme im 90-Grad-Winkel, lehne dich nach vorne.", notes: "Verschiedene Armhöhen für verschiedene Bereiche.", animationKey: "doorway_stretch" },
  { index: 10096, name: "Downward Dog", categories: ["Stretching", "Back"], muscles: ["hamstrings","calves","shoulders","back"], musclesLatin: ["musculi ischiocrurale","musculus gastrocnemius","musculus deltoideus","musculus latissimus dorsi"], shortDescription: "Aus dem Vierfüßlerstand Hüfte nach oben drücken in eine umgekehrte V-Form.", notes: "Rücken gerade. Fersen Richtung Boden drücken.", animationKey: "downward_dog" },
  { index: 10097, name: "World's Greatest Stretch", categories: ["Stretching", "Full Body"], muscles: ["hip-flexors","back","shoulders","hamstrings"], musclesLatin: ["musculus iliopsoas","musculus erector spinae","musculus deltoideus","musculi ischiocrurale"], shortDescription: "Ausfallschritt, eine Hand am Boden, andere Hand zur Decke rotieren.", notes: "Große Rotation. Tiefe Ausfallschrittposition.", animationKey: "worlds_greatest" },
  { index: 10098, name: "Lunge with Twist", categories: ["Stretching", "Core"], muscles: ["hip-flexors","obliques"], musclesLatin: ["musculus iliopsoas","musculus obliquus externus abdominis"], shortDescription: "Im Ausfallschritt, rotiere den Oberkörper zum vorderen Knie.", notes: "Tiefe Ausfallschrittposition. Blick folgt der Hand.", animationKey: "lunge_twist" },
];

/**
 * Returns the primary category string for an exercise (first in categories array).
 * Falls back to 'category' field for backward compatibility.
 */
export function getPrimaryCategory(exercise) {
  if (exercise.categories && exercise.categories.length > 0) return exercise.categories[0];
  return exercise.category || '';
}

/**
 * Returns a display-friendly muscles string from the muscles array.
 */
export function getMusclesDisplay(exercise) {
  if (exercise.muscles && exercise.muscles.length > 0) {
    return exercise.muscles.join(', ');
  }
  return exercise.muscles_legacy || '';
}